# Generated by Django 5.2 on 2025-05-03 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BILLING', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_no',
        ),
    ]
