# Generated by Django 5.2 on 2025-06-11 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BILLING', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='sub_total',
        ),
    ]
