# Generated by Django 5.2 on 2025-06-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BILLING', '0002_remove_cartitem_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
