# Generated by Django 5.2 on 2025-05-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BILLING', '0002_remove_invoice_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
    ]
