# Generated by Django 5.2 on 2025-05-05 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BILLING', '0003_invoice_invoice_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='total',
            new_name='grand_total',
        ),
    ]
