# Generated by Django 5.2 on 2025-05-06 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BILLING', '0004_rename_total_invoice_grand_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_no',
        ),
    ]
