# Generated by Django 5.2 on 2025-05-22 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BILLING', '0004_invoiceitem'),
        ('CUSTOMER', '0002_alter_customer_phone'),
        ('PRODUCT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CUSTOMER.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRODUCT.product')),
            ],
        ),
    ]
