# Generated by Django 5.2 on 2025-05-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BILLING', '0006_alter_invoice_grand_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
