# Generated by Django 5.2 on 2025-05-23 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BILLING', '0007_alter_cart_grand_total_alter_cart_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='quantity',
        ),
    ]
