# Generated by Django 5.2 on 2025-05-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BILLING', '0009_invoiceitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='sub_total',
        ),
        migrations.AddField(
            model_name='cart',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
