# Generated by Django 5.2 on 2025-05-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BILLING', '0010_remove_invoiceitem_sub_total_cart_gst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='gst',
        ),
        migrations.AddField(
            model_name='cart',
            name='gst_percentage',
            field=models.IntegerField(default=5),
        ),
    ]
