# Generated by Django 5.2 on 2025-05-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BILLING', '0011_remove_cart_gst_cart_gst_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
