# Generated by Django 5.2 on 2025-05-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BILLING', '0012_cart_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='gst_percentage',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='gst_percentage',
            field=models.IntegerField(default=2),
        ),
    ]
