# Generated by Django 5.2 on 2025-05-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BILLING', '0013_alter_cart_gst_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='gst_percentage',
            field=models.IntegerField(default=0.5),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='gst_percentage',
            field=models.IntegerField(default=0.5),
        ),
    ]
