# Generated by Django 5.2 on 2025-05-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BILLING', '0014_alter_cart_gst_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='gst_percentage',
            field=models.IntegerField(default=1.6),
        ),
    ]
