# Generated by Django 5.2 on 2025-05-26 11:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BILLING', '0016_alter_cart_gst_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='gst_percentage',
            field=models.IntegerField(default=Decimal('0.6')),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='gst_percentage',
            field=models.IntegerField(default=Decimal('0.6')),
        ),
    ]
