# Generated by Django 5.2 on 2025-05-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BILLING', '0018_alter_cart_gst_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
