# Generated by Django 5.2 on 2025-05-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BILLING', '0019_invoice_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
