# Generated by Django 5.2 on 2025-06-13 09:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUSTOMER', '0004_customer_credit_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10),
        ),
    ]
