# Generated by Django 5.2 on 2025-05-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0004_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('groceries', 'Groceries'), ('suppliers', 'Suppliers'), ('other', 'Other')], max_length=255, null=True),
        ),
    ]
