# Generated by Django 5.2 on 2025-04-26 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN_APP', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
